name: Node.js CI/CD on Amazon Linux

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install

    - name: Deploy to AWS EC2
      uses: appleboy/scp-action@master
      with:
        host: ${{ REMOTE_HOST }}
        username: ${{ REMOTE_USER }}
        key: ${{ SSH_PRIVATE_KEY }}
        source: "./"  # This now correctly points to the current directory
        target: "/var/www/proyecto"

    - name: Restart PM2 application
      uses: appleboy/ssh-action@master
      with:
        host: ${{ REMOTE_HOST }}
        username: ${{ REMOTE_USER }}
        key: ${{ SSH_PRIVATE_KEY }}
        script: |
          cd /var/www/proyecto
          pm2 reload all  # This command restarts your application
